version: '3'
services:
  web:
    image: odoo:8.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /odoo/config:/etc/odoo
      - /odoo/addons:/mnt/extra-addons
      - /odoo/log:/var/log/odoo
      - /odoo/data:/var/lib/odoo   
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: