version: "2"
services:
  postgres:
    image: postgres:11.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /postgresql/data:/var/lib/postgresql/data/pgdata
  odoo:
    image: newtratip/odoo:12.0
    container_name: odoo
    restart: always
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - /odoo/addons:/mnt/extra-addons
      - /odoo/config:/etc/odoo
      - /odoo/log:/var/log/odoo
      - /odoo/data:/var/lib/odoo
    depends_on:
      - postgres
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80      
    volumes:
      - /nginx/config:/etc/nginx/conf.d
      - /nginx/log:/var/log/nginx
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "1000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - /pgadmin/data:/var/lib/pgadmin
