version: "3"
services:
  web:
    image: newtratip/odoo:8.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - PORT=5432
      - POSTGRES_USER=odoo
      - PASSWORD=odoo
    volumes:
      - /odoo/addons:/mnt/extra-addons
      - /odoo/config:/etc/odoo
      - /odoo/log:/var/log/odoo
      - /odoo/data:/var/lib/odoo
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /postgres/data:/var/lib/postgresql/data/pgdata
  nginx:
    image: nginx
    volumes:
      - /nginx/config:/etc/nginx/conf.d
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80