version: "2"
services:
  postgres:
    image: postgres:9.5
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=openerp
      - POSTGRES_USER=openerp
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /postgresql/data:/var/lib/postgresql/data/pgdata
  odoo:
    image: newtratip/odoo:7.0
    container_name: odoo
    command: start
    restart: always
    ports:
      - "8069:8069"
    environment:
      - ODOO_DB_USER=openerp
      - ODOO_DB_PASSWORD=openerp
    volumes:
      - /odoo/addons:/opt/odoo/additional_addons
      - /odoo/data/filestore:/opt/odoo/sources/odoo/openerp/filestore
      - /odoo/etc:/opt/odoo/etc
    links:
      - postgres:db    
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80      
    volumes:
      - /nginx/config:/etc/nginx/conf.d
      - /nginx/log:/var/log/nginx
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "1000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - /pgadmin/data:/var/lib/pgadmin
